spring:
  #db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k10c109.p.ssafy.io:10912/trigger?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/trigger?serverTimezone=Asia/Seoul
    username: root
    password: trigger109!
#    password: 1234
  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  #oauth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 402852256675-iorg86ch98fno95pcmfafu02j493sjpi.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: AGjSJdK8sZLFOW8C6Ac3
            client-secret: NJS5MZwJOw
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
          kakao:
            client-id: 3629b7ba00a3e7f17746ba4978948456
            client-secret: eduCsFry62yfF3xle1K1Sif9SO5znaeg
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#  data:
#    redis:
#      host: 192.168.99.100
#      port: 6379

jwt:
  secretKey: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa

  access:
    expiration: 1209600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh


#AWS S3
cloud:
  aws:
    credentials:
      access-key: AKIAQ3EGSCUZF6M3J4HW
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: trigger109-bucket
    stack:
      auto: false